name: Run Cypress

on: [deployment_status]

jobs:
  test:
    if: github.event.deployment_status.state == 'success' github.event.deployment_status.environment == 'Preview'
    name: Run Cypress
    runs-on: ubuntu-20.04
    steps:
      - name: --- State -------------------------
        run: echo ${{github.event.deployment_status.state}}
      - name: --- Environment -------------------
        run: echo ${{github.event.deployment_status.environment}}
      - name: --- Environment URL ---------------
        run: echo ${{github.event.deployment_status.environment_url}}
      - name: --- Target URL --------------------
        run: echo ${{github.event.deployment_status.target_url}}

      - uses: actions/checkout@v3

      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - run: yarn run prebuild

      - uses: cypress-io/github-action@v4
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
